### ISSUE TITLE
Add contribution.md and code_of_conduct file.

### ISSUE THREAD

**Issue by chemben17** [thevkrant/hello-world#2]
it's not the best thing to leave both both files **contribution.md and code_of_conduct**  out of your root file.
Both help with rules on how to go about successfully pull request and also to maintain the community order.

## Solution
There are famous written code_of_conducts that you might find matching and sane, you can just for them or just copy and implement them.

**Comment by thevkrant** [comment]
Thanks for the suggestion and helpful solution. I'll be work on it soon.

**Comment by chemben17** [comment]
You're welcome. I can also work on it
